### ISSUE TITLE
Pick class list to label the images

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/tinyCAML#10]
You will need to modify the classes.txt file in doodler.

You want something that has a bunch of classes, but it does not need to be exhaustive:

'water'
'road'
'vehicle'
'building'
'vegetation'
'other' (i.e., bikes, people, gravel on side of road, telephone poles)

@anardek - we will need your help here..

The goal will to be to have a very nice set of classes for each picture.. Keep in mind, that with a small dataset, we will likely merge classes and build a model with just 2 classes (water, not water), or 3 maybe (water, road, not water nor road). BUT it is helpful to have a bunch of classes for experiments in the future..

**Comment by anardek** [comment]
@JoeWTG - can we go through this during our meeting on Friday? Does this mean you want me to label the images with the 5 different classes? Or help decide on the classes themselves?

**Comment by ebgoldstein** [comment]
@anardek - Help decide the classes themselves

**Comment by ebgoldstein** [comment]
and just to clarify - when labeling Joe can/should have a bunch of classes to chose for each image.. and then before the ML we can combine classes 'on-the-fly'...

**Comment by anardek** [comment]
Understood. Since we will be using the Beaufort camera -- and there is no vegetation in that image -- I suggest:
'water'
'road'
'vehicle'
'building'
'people'
'other' (i.e., bikes, dogs, birds)

**Comment by ebgoldstein** [comment]
sounds good. @JoeWTG , once you modify the classes.txt file to reflect this list, feel free to close this issue

**Comment by anardek** [comment]
After talking with Joe, new classes are:
- water
- road
- sidewalk
- vehicle
- building
- people
- other

Some things to think about later: 
1) water on road vs water on sidewalk
2) do we classify the sun glare from the dome?

**Comment by Bolewitz** [comment]
Example of the sun glare that is seen in some of the images
![CAM_BF_01_20220517001822 resize](https://user-images.githubusercontent.com/11952593/179266105-b7aca9d8-7a13-4f74-ba4a-ca887348f583.jpg)

**Comment by anardek** [comment]
@JoeWTG - 
- [ ] upload the doodles, labels, and models to the drive
- [ ] create a spreadsheet for tracking labels (see the example from the main directory on the drive): i.e., purpose, source of images, labeler, number of labels, date, where located

**Comment by ebgoldstein** [comment]
> water on road vs water on sidewalk

My thinking is this: If the goal is to determine if water is on the road, then we will make a 3 class segmentation model for 'water', 'road', 'other'. Then there is a nonML routine that determines if {water and road classes are adjacent} OR if {water class is surrounded by road} or some sort of rule... So water surrounded by sidewalk (classified as 'other'), then this rule will determine that the road is not flooded..

I am not sure if you are thinking about different classes for road vs sidewalk water... IF you want to do sidewalk water different than road water, then the classes could be 'water on sidewalk' and 'water on road'.. but i think this is not needed..

> do we classify the sun glare from the dome?

good point - yes the pixels for sun glare will need to be classified b/c doodler labels every pixel in an image. I would classify the sun glare in the 'other' class OR make a new 'sun glare' class... I suggest just putting it 'other'

**Comment by ebgoldstein** [comment]
as for preserving the output of doodler - make sure to save all the files in the results folder to the G. Drive.

**Comment by anardek** [comment]
> My thinking is this: If the goal is to determine if water is on the road, then we will make a 3 class segmentation model for 'water', 'road', 'other'. Then there is a nonML routine that determines if {water and road classes are adjacent} OR if {water class is surrounded by road} or some sort of rule... So water surrounded by sidewalk (classified as 'other'), then this rule will determine that the road is not flooded..

Ok, I'm fine with this. Seems less complicated. Same with the sun glare. @JoeWTG - let us know if this makes sense.

**Comment by ebgoldstein** [comment]
i am closing this issue.. i moved @anardek list above into issue #12
