### ISSUE TITLE
Use doodled images to make a segmentation model 

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/tinyCAML#13]
2 steps:
1. template notebook, just to learn how segmentation works: https://github.com/ebgoldstein/Coastal_TF_templates/blob/main/src/SimpleUnet.ipynb
2. Use Gym, for better model : https://github.com/Doodleverse/segmentation_gym

**Comment by Bolewitz** [comment]
added in [unet_model_trainer.ipynb](https://github.com/UNCG-DAISY/tinyCamML/blob/main/ML/src/unet_model_trainer.ipynb). 

Will look into Gym during the fall semester.
