### ISSUE TITLE
remap classes function

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/tinyCAML#14]
Images have 7 classes:

> water
> road
> building
> sidewalk
> vehicle
> people
> other

Write a fn that reduces the 7 class image (all pixels 0-6) to a smller number of classses (i.e., 0-1 or 0-2) by merging classes in a user defined way..

Initially we will want to work with 3 classes: `water`, `road` and `not-water-nor-road` (i.e., all other classes).. so that would be an image where all pixels are either 0 (water), 1 (road), 2 (all other classes)..

**Comment by Bolewitz** [comment]
added in [43746f4](https://github.com/UNCG-DAISY/tinyCamML/commit/43746f4733b10e5d5444bcf1ac10e6aee53b2e57) as [class_remapper.ipynb](https://github.com/UNCG-DAISY/tinyCamML/blob/main/ML/src/class_remapper.ipynb).
