### ISSUE TITLE
Deploy model on device

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/tinyCAML#4]
put quantized model on ESP32-Cam and confirm that it works ( save on model 'inference' results + images on SD card and inspect results)

**Comment by Bolewitz** [comment]
initial code uploaded in [1a1749e](https://github.com/UNCG-DAISY/tinyCamML/commit/1a1749ef3a37ed27e83c288478115326267f51bb)

trying to use the EloquentTinyML library to make inference on the ESP32-CAM easier to create. 
Having issue when compiling, need to determine the correct values for N_INPUTS and TENSOR_ARENA_SIZE.

**Comment by Bolewitz** [comment]
https://smartmicrotech.it/eloquent-tinyml/person-detection/
The current example I've been working off of. Was able to get it running on the ESP32-CAM, just need to add my model and see if it works.

**Comment by ebgoldstein** [comment]
will not be done in this repo - close via https://github.com/UNCG-DAISY/tinyCamML/commit/3ecf1e50c92de5706976845c6996e87409ce633f
