### ISSUE TITLE
Label Beaufort flooding no flooding images

### ISSUE THREAD

**Issue by Bolewitz** [UNCG-DAISY/tinyCAML#7]
100 flooding, 100 not-flooding

**Comment by anardek** [comment]
I added a script from Adam Gold to pull images of flooding from our database: [60b3bec](https://github.com/UNCG-DAISY/tinyCAML/commit/60b3bec14846f663b4197e7ffb3ec5c6fb7f2471)

**Comment by anardek** [comment]
@JoeWTG - Adam and I got the script to work. I uploaded the images to the shared Google Drive.

A couple notes:
1. You will need to QC these images. From my limited review, it looks like there may be some flooding that is blocked by cars.
2. You need to create a folder of images with no flooding. To do this, you will need to go in to the drive for CAM_BF_01 and choose these photos yourself.

**Comment by anardek** [comment]
@JoeWTG - please upload the labeled images to Google Drive. I already uploaded the labels.

**Comment by Bolewitz** [comment]
I've uploaded the labeled images to Google Drive and updated the .csv files with the labels. I had issues earlier today trying to upload the images individually so I uploaded them as a .zip for now.
