### ISSUE TITLE
Pick a single camera/set of images to doodle and load into doodler

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/tinyCAML#9]
Its easiest if you focus on 1 camera for the first round of segmentation. @anardek , do you have a preferred camera to work with?
Use the images that you already classified into flooded/not flooded. Maybe take 30 pictures total for segmentation (i would do 10 not flooded, 20 flooded). Put those selected images into the Doodler `/Assets/` folder.

**Comment by anardek** [comment]
@JoeWTG - lets use the Beaufort camera since it has the most images.

**Comment by ebgoldstein** [comment]
cool - Beaufort cam. @JoeWTG , feel free to close this issue when you have selected the images to doodle ( from your directory of labeled of flood/no flood images)
